export const SET_RESERVATIONS = "SET_RESERVATIONS";
export const SET_EMPLOYEE_COUNT = "SET_EMPLOYEE_COUNT";
export const SET_DESKS_RESULTS = "SET_DESKS_RESULTS";
export const CHECK_MORE = "CHECK_MORE";
export const SET_PAGE = "SET_PAGE";
export const SET_FILTER = "SET_FILTER";
export const SET_OFFICES = "SET_OFFICES";
export const SET_DESKS = "SET_DESKS";
export const SET_FLOORPLAN_AVAILABLE = "SET_FLOORPLAN_AVAILABLE";

export const SET_MSAL_INSTANCE = "SET_MSAL_INSTANCE";
export const GET_MSAL_INSTANCE = "GET_MSAL_INSTANCE";

export const SET_USER_ADDED_TO_DB = "SET_USER_ADDED_TO_DB";
export const SET_USER_DISPLAY_NAME = "SET_USER_DISPLAY_NAME";
export const SET_PROFILE_PHOTO = "SET_PROFILE_PHOTO";
export const SET_OID = "SET_OID";
export const SET_IS_ADMIN = "SET_IS_ADMIN";
